# Installing Libraries

In [2]:
!pip3 install scikit-learn pandas numpy seaborn matplotlib

Collecting scikit-learn
  Using cached scikit_learn-1.8.0-cp313-cp313-win_amd64.whl.metadata (11 kB)
Collecting pandas
  Using cached pandas-3.0.2-cp313-cp313-win_amd64.whl.metadata (19 kB)
Collecting numpy
  Using cached numpy-2.4.4-cp313-cp313-win_amd64.whl.metadata (6.6 kB)
Collecting seaborn
  Using cached seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Collecting matplotlib
  Using cached matplotlib-3.10.8-cp313-cp313-win_amd64.whl.metadata (52 kB)
Collecting scipy>=1.10.0 (from scikit-learn)
  Using cached scipy-1.17.1-cp313-cp313-win_amd64.whl.metadata (60 kB)
Collecting joblib>=1.3.0 (from scikit-learn)
  Using cached joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting threadpoolctl>=3.2.0 (from scikit-learn)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in .\.venv\Lib\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Using cached tzdata-2026.1-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting contourpy>=1.0.1 (from matplotlib)
  Using cached contourpy-1.3.3-cp313-cp313-win_amd64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib)
  Using cached fonttools-4.62.1-cp313-cp313-win_amd64.whl.metadata (119 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Using cached kiwisolver-1.5.0-cp313-cp313-win_amd64.whl.metadata (5.2 kB)
Requirement already satisfied: packaging>=20.0 in .\.venv\Lib\site-packages (from matplotlib) (26.1)
Collecting pillow>=8 (from matplotlib)
  Using cached pillow-12.2.0-cp313-cp313-win_amd64.whl.metadata (9.0 kB)
Collecting pyparsing>=3 (from matplotlib)
  Using cached pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: six>=1.5 in .\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached scikit_learn-1.8.0-cp313-cp313-win_amd64.whl (8.0 MB)
Using cached pandas-3.0.2-cp313-cp313-win_amd64.whl (9.7 MB)
Using cached numpy-2.4.4-cp313-cp313-win_amd64.whl (12.3 MB)
Using cached seaborn-0.13.2-py3-none-any.whl (294 kB)
Using cached matplotlib-3.10.8-cp313-cp313-win_amd64.whl (8.1 MB)
Using cached contourpy-1.3.3-cp313-cp313-win_amd64.whl (226 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Using cached fonttools-4.62.1-cp313-cp313-win_amd64.whl (2.3 MB)
Using cached joblib-1.5.3-py3-none-any.whl (309 kB)
Using cached kiwisolver-1.5.0-cp313-cp313-win_amd64.whl (73 kB)
Using cached pillow-12.2.0-cp313-cp313-win_amd64.whl (7.1 MB)
Using cached pyparsing-3.3.2-py3-none-any.whl (122 kB)
Using cached scipy-1.17.1-cp313-cp313-win_amd64.whl (36.5 MB)
Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Using cached tzdata-2026.1-py2.py3-none-any.whl (348 kB)
Installing collected packages: tzdata, threadpoolctl, pyparsing, pillow, numpy, kiwisolver, joblib, fonttools, cycler, scipy, pandas, contourpy, scikit-learn, matplotlib, seaborn

   ----------------------------------------  0/15 [tzdata]
   ----------------------------------------  0/15 [tzdata]
   ----------------------------------------  0/15 [tzdata]
   ----------------------------------------  0/15 [tzdata]
   ----------------------------------------  0/15 [tzdata]
   ----------------------------------------  0/15 [tzdata]
   ----------------------------------------  0/15 [tzdata]
   ----------------------------------------  0/15 [tzdata]
   -- -------------------------------------  1/15 [threadpoolctl]
   ----- ----------------------------------  2/15 [pyparsing]
   ----- ----------------------------------  2/15 [pyparsing]
   ----- ----------------------------------  2/15 [pyparsing]
   -------- -------------------------------  3/15 [pillow]
   -------- -------------------------------  3/15 [pillow]
   -------- -------------------------------  3/15 [pillow]
   -------- -------------------------------  3/15 [pillow]
   -------- -------------------------------  3/15 [pillow]
   -------- -------------------------------  3/15 [pillow]
   -------- -------------------------------  3/15 [pillow]
   -------- -------------------------------  3/15 [pillow]
   -------- -------------------------------  3/15 [pillow]
   -------- -------------------------------  3/15 [pillow]
   -------- -------------------------------  3/15 [pillow]
   -------- -------------------------------  3/15 [pillow]
   -------- -------------------------------  3/15 [pillow]
   -------- -------------------------------  3/15 [pillow]
   -------- -------------------------------  3/15 [pillow]
   -------- -------------------------------  3/15 [pillow]
   -------- -------------------------------  3/15 [pillow]
   -------- -------------------------------  3/15 [pillow]
   -------- -------------------------------  3/15 [pillow]
   -------- -------------------------------  3/15 [pillow]
   -------- -------------------------------  3/15 [pillow]
   -------- -------------------------------  3/15 [pillow]
   -------- -------------------------------  3/15 [pillow]
   -------- -------------------------------  3/15 [pillow]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ------------- --------------------------  5/15 [kiwisolver]
   ---------------- -----------------------  6/15 [joblib]
   ---------------- -----------------------  6/15 [joblib]
   ---------------- -----------------------  6/15 [joblib]
   ---------------- -----------------------  6/15 [joblib]
   ---------------- -----------------------  6/15 [joblib]
   ---------------- -----------------------  6/15 [joblib]
   ---------------- -----------------------  6/15 [joblib]
   ---------------- -----------------------  6/15 [joblib]
   ---------------- -----------------------  6/15 [joblib]
   ---------------- -----------------------  6/15 [joblib]
   ---------------- -----------------------  6/15 [joblib]
   ---------------- -----------------------  6/15 [joblib]
   ---------------- -----------------------  6/15 [joblib]
   ---------------- -----------------------  6/15 [joblib]
   ---------------- -----------------------  6/15 [joblib]
   ---------------- -----------------------  6/15 [joblib]
   ---------------- -----------------------  6/15 [joblib]
   ---------------- -----------------------  6/15 [joblib]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   --------------------- ------------------  8/15 [cycler]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]

# Loading the CSV into DataFrame

In [6]:
import pandas as pd
import numpy as np

df = pd.read_csv("Sample - Superstore.csv" , encoding="'ISO-8859-1'")
df.head(2)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.0,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.0,219.5820

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   str
 2   Order Date     9994 non-null   str
 3   Ship Date      9994 non-null   str
 4   Ship Mode      9994 non-null   str
 5   Customer ID    9994 non-null   str
 6   Customer Name  9994 non-null   str
 7   Segment        9994 non-null   str
 8   Country        9994 non-null   str
 9   City           9994 non-null   str
 10  State          9994 non-null   str
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   str
 13  Product ID     9994 non-null   str
 14  Category       9994 non-null   str
 15  Sub-Category   9994 non-null   str
 16  Product Name   9994 non-null   str
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), str(15)
memory usage: 1.6 MB

In [8]:
df.columns.tolist()

['Row ID',
 'Order ID',
 'Order Date',
 'Ship Date',
 'Ship Mode',
 'Customer ID',
 'Customer Name',
 'Segment',
 'Country',
 'City',
 'State',
 'Postal Code',
 'Region',
 'Product ID',
 'Category',
 'Sub-Category',
 'Product Name',
 'Sales',
 'Quantity',
 'Discount',
 'Profit']

In [9]:
df.describe()

,Row ID,Postal Code,Sales,Quantity,Discount,Profit
count,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,4997.500000,55190.379428,229.858001,3.789574,0.156203,28.656896
std,2885.163629,32063.693350,623.245101,2.225110,0.206452,234.260108
min,1.000000,1040.000000,0.444000,1.000000,0.000000,-6599.978000
25%,2499.250000,23223.000000,17.280000,2.000000,0.000000,1.728750
50%,4997.500000,56430.500000,54.490000,3.000000,0.200000,8.666500
75%,7495.750000,90008.000000,209.940000,5.000000,0.200000,29.364000
max,9994.000000,99301.000000,22638.480000,14.000000,0.800000,8399.976000

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df.dtypes

Row ID             int64
Order ID             str
Order Date           str
Ship Date            str
Ship Mode            str
Customer ID          str
Customer Name        str
Segment              str
Country              str
City                 str
State                str
Postal Code        int64
Region               str
Product ID           str
Category             str
Sub-Category         str
Product Name         str
Sales            float64
Quantity           int64
Discount         float64
Profit           float64
dtype: object

# feature selection and dropping unwanted features

In [12]:
df.columns.tolist()

['Row ID',
 'Order ID',
 'Order Date',
 'Ship Date',
 'Ship Mode',
 'Customer ID',
 'Customer Name',
 'Segment',
 'Country',
 'City',
 'State',
 'Postal Code',
 'Region',
 'Product ID',
 'Category',
 'Sub-Category',
 'Product Name',
 'Sales',
 'Quantity',
 'Discount',
 'Profit']

In [13]:
df.head(1)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.0,41.9136

In [65]:
df['Sub-Category'].unique()

<StringArray>
[  'Bookcases',      'Chairs',      'Labels',      'Tables',     'Storage',
 'Furnishings',         'Art',      'Phones',     'Binders',  'Appliances',
       'Paper', 'Accessories',   'Envelopes',   'Fasteners',    'Supplies',
    'Machines',     'Copiers']
Length: 17, dtype: str

Grouping the Sub - Category column wiht some unique values with other_categories option

In [73]:
sub_cat = df['Sub-Category'].value_counts()

rare_cat = sub_cat[sub_cat < 300].index.tolist()

df['Sub-Category'] = df['Sub-Category'].replace(rare_cat, "other_categories")

df['Sub-Category'].value_counts()

Sub-Category
Binders             1523
Paper               1370
other_categories    1072
Furnishings          957
Phones               889
Storage              846
Art                  796
Accessories          775
Chairs               617
Appliances           466
Labels               364
Tables               319
Name: count, dtype: int64

Grouping some unique values with others option

In [58]:
least_states = df['State'].value_counts()

In [64]:
rare_states = least_states[least_states < 100].index.tolist()
print(rare_states)

df['State'] = df['State'].replace(rare_states , "Others")

df['State'].value_counts()
print(len(df['State'].value_counts()))

['Delaware', 'Minnesota', 'Connecticut', 'Missouri', 'Oklahoma', 'Alabama', 'Arkansas', 'Rhode Island', 'Utah', 'Mississippi', 'South Carolina', 'Louisiana', 'Nevada', 'Nebraska', 'New Mexico', 'Iowa', 'New Hampshire', 'Kansas', 'Idaho', 'Montana', 'South Dakota', 'Vermont', 'District of Columbia', 'Maine', 'North Dakota', 'West Virginia', 'Wyoming']
23

In [80]:
# Extracting the date and year from Order date column

df['Order Date'] = pd.to_datetime(df['Order Date'])

df['Order Year'] = df['Order Date'].dt.year
df['Order Month'] = df['Order Date'].dt.month

df.head(1)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Order Year,Order Month
0,1,CA-2016-152156,2016-11-08,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,FUR-BO-10001798,Furniture,other_categories,Bush Somerset Collection Bookcase,261.96,2,0.0,41.9136,2016,11

In [ ]:
#  'Ship Mode', 'Segment', 'State', 'Region', 'Category', 'Sub-Category', 'Sales', 'Quantity', 'Discount', 'Profit'

In [78]:
print(df.columns.tolist(), end=",")

['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State', 'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category', 'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],

In [81]:
# Dropping the columns

df = df.drop(['Order Date','Row ID', 'Order ID', 'Ship Date','Country', 'Customer ID', 'Customer Name',  'City', 'Postal Code', 'Product ID', 'Product Name'],axis =1)

df

,Ship Mode,Segment,State,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit,Order Year,Order Month
0,Second Class,Consumer,Kentucky,South,Furniture,other_categories,261.9600,2,0.00,41.9136,2016,11
1,Second Class,Consumer,Kentucky,South,Furniture,Chairs,731.9400,3,0.00,219.5820,2016,11
2,Second Class,Corporate,California,West,Office Supplies,Labels,14.6200,2,0.00,6.8714,2016,6
3,Standard Class,Consumer,Florida,South,Furniture,Tables,957.5775,5,0.45,-383.0310,2015,10
4,Standard Class,Consumer,Florida,South,Office Supplies,Storage,22.3680,2,0.20,2.5164,2015,10
...,...,...,...,...,...,...,...,...,...,...,...,...
9989,Second Class,Consumer,Florida,South,Furniture,Furnishings,25.2480,3,0.20,4.1028,2014,1
9990,Standard Class,Consumer,California,West,Furniture,Furnishings,91.9600,2,0.00,15.6332,2017,2
9991,Standard Class,Consumer,California,West,Technology,Phones,258.5760,2,0.20,19.3932,2017,2
9992,Standard Class,Consumer,California,West,Office Supplies,Paper,29.6000,4,0.00,13.3200,2017,2
9993,Second Class,Consumer,California,West,Office Supplies,Appliances,243.1600,2,0.00,72.9480,2017,5

# Encoding the Categorical Features

In [ ]:
# Onehot Encoding 
df = pd.get_dummies(df , columns=['Ship Mode','Segment','State','Region','Category','Sub-Category'], drop_first=True)

KeyError: "None of [Index(['Ship Mode', 'Segment', 'State', 'Region', 'Category', 'Sub-Category'], dtype='str')] are in the [columns]"

In [87]:
df.head(5)

,Sales,Quantity,Discount,Profit,Order Year,Order Month,Ship Mode_Same Day,Ship Mode_Second Class,Ship Mode_Standard Class,Segment_Corporate,...,Sub-Category_Art,Sub-Category_Binders,Sub-Category_Chairs,Sub-Category_Furnishings,Sub-Category_Labels,Sub-Category_Paper,Sub-Category_Phones,Sub-Category_Storage,Sub-Category_Tables,Sub-Category_other_categories
0,261.9600,2,0.00,41.9136,2016,11,False,True,False,False,...,False,False,False,False,False,False,False,False,False,True
1,731.9400,3,0.00,219.5820,2016,11,False,True,False,False,...,False,False,True,False,False,False,False,False,False,False
2,14.6200,2,0.00,6.8714,2016,6,False,True,False,True,...,False,False,False,False,True,False,False,False,False,False
3,957.5775,5,0.45,-383.0310,2015,10,False,False,True,False,...,False,False,False,False,False,False,False,False,True,False
4,22.3680,2,0.20,2.5164,2015,10,False,False,True,False,...,False,False,False,False,False,False,False,True,False,False